//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaDoZe.Properties.Resources-en-US", typeof(Resources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer registration.
        /// </summary>
        public static string btnCadastrarCliente_Text {
            get {
                return ResourceManager.GetString("btnCadastrarCliente.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Registration.
        /// </summary>
        public static string btnCadastrarProduto_Text {
            get {
                return ResourceManager.GetString("btnCadastrarProduto.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee registration.
        /// </summary>
        public static string btnCadastroDeFuncionarios_Text {
            get {
                return ResourceManager.GetString("btnCadastroDeFuncionarios.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register of ingredients.
        /// </summary>
        public static string btnCadastroDeIngredientes_Text {
            get {
                return ResourceManager.GetString("btnCadastroDeIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flavors Registration.
        /// </summary>
        public static string btnCadastroDeSabores_Text {
            get {
                return ResourceManager.GetString("btnCadastroDeSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of values.
        /// </summary>
        public static string btnCadastroValores_Text {
            get {
                return ResourceManager.GetString("btnCadastroValores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancelar_Text {
            get {
                return ResourceManager.GetString("btnCancelar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To clean.
        /// </summary>
        public static string btnLimpar_Text {
            get {
                return ResourceManager.GetString("btnLimpar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To save.
        /// </summary>
        public static string btnSalvar_Text {
            get {
                return ResourceManager.GetString("btnSalvar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighborhood.
        /// </summary>
        public static string labelBairro_Text {
            get {
                return ResourceManager.GetString("labelBairro.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string labelCategoria_Text {
            get {
                return ResourceManager.GetString("labelCategoria.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNH.
        /// </summary>
        public static string labelCnh_Text {
            get {
                return ResourceManager.GetString("labelCnh.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement.
        /// </summary>
        public static string labelComplemento_Text {
            get {
                return ResourceManager.GetString("labelComplemento.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string labelCpf_Text {
            get {
                return ResourceManager.GetString("labelCpf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string labelEmail_Text {
            get {
                return ResourceManager.GetString("labelEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string labelFuncao_Text {
            get {
                return ResourceManager.GetString("labelFuncao.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string labelIngredientes_Text {
            get {
                return ResourceManager.GetString("labelIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zé pizzeria.
        /// </summary>
        public static string labelLogo_Text {
            get {
                return ResourceManager.GetString("labelLogo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string LabelMl_Text {
            get {
                return ResourceManager.GetString("LabelMl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string labelNome_Text {
            get {
                return ResourceManager.GetString("labelNome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        public static string labelRua_Text {
            get {
                return ResourceManager.GetString("labelRua.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string labelSenha_Text {
            get {
                return ResourceManager.GetString("labelSenha.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string labelTamanho_Text {
            get {
                return ResourceManager.GetString("labelTamanho.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string labelTelefone_Text {
            get {
                return ResourceManager.GetString("labelTelefone.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string labelTipo_Text {
            get {
                return ResourceManager.GetString("labelTipo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNH validity.
        /// </summary>
        public static string labelValidadecnh_Text {
            get {
                return ResourceManager.GetString("labelValidadecnh.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string LabelValor_Text {
            get {
                return ResourceManager.GetString("LabelValor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border value.
        /// </summary>
        public static string labelValorBorda_Text {
            get {
                return ResourceManager.GetString("labelValorBorda.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special value.
        /// </summary>
        public static string LabelValorEspecial_Text {
            get {
                return ResourceManager.GetString("LabelValorEspecial.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional value.
        /// </summary>
        public static string labelValorTradicional_Text {
            get {
                return ResourceManager.GetString("labelValorTradicional.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string ListarClientes_Text {
            get {
                return ResourceManager.GetString("ListarClientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string ListarFuncionários_Text {
            get {
                return ResourceManager.GetString("ListarFuncionários.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredients.
        /// </summary>
        public static string ListarIngredientes_Text {
            get {
                return ResourceManager.GetString("ListarIngredientes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ListarProdutos_Text {
            get {
                return ResourceManager.GetString("ListarProdutos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flavors.
        /// </summary>
        public static string ListarSabores_Text {
            get {
                return ResourceManager.GetString("ListarSabores.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizes.
        /// </summary>
        public static string ListarTamanhos_Text {
            get {
                return ResourceManager.GetString("ListarTamanhos.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main screen.
        /// </summary>
        public static string Telalabel_Text {
            get {
                return ResourceManager.GetString("Telalabel.Text", resourceCulture);
            }
        }
    }
}
